/* silken_net_audio_model.h — AUTO-GENERATED by silken_ml.export. DO NOT EDIT.
 *
 * Baseline per-frame INT8 acoustic classifier: 40 log-mel -> 5 classes
 * (silence/wind/cavitation/chainsaw/fauna). Self-owned ESC-50 baseline that
 * UNBLOCKS FW.4 — replaces silken_net_audio_model_stub.h via __has_include.
 *
 * Provenance: run 20260612T204428 | float-acc 0.8558 | int8-acc 0.8541 | data-manifest 4147c92422be3949
 *   ^ MIXED corpus: silence + cavitation are SYNTHETIC placeholders (2/5 classes) —
 *   a pipeline-integrity metric, NOT field accuracy; cavitation is NOT field-validated.
 *   Per-class validity: docs/03_03 §4.2 / tools/ml/docs/baseline_model_program.md §2.1.
 * Quant parity vs TFLite: argmax-exact, max|d logit|=1 (n=5318).
 * Log-mel contract hash 0cd21eb3c2d89ac6 (docs/03_03 §3.4) — RETRAIN if it changes.
 *
 * Runtime: self-contained integer forward pass (gemmlowp requantize); NO TFLM /
 * CMSIS-NN dependency (docs/03_03 runtime reconciliation; weights -> Flash const,
 * activations -> stack, ~0 .bss). Program: tools/ml/docs/baseline_model_program.md.
 */
#ifndef SILKEN_NET_AUDIO_MODEL_H
#define SILKEN_NET_AUDIO_MODEL_H

#include <stdint.h>
#include <math.h>

/* === Class contract (matches silken_net_audio_model_stub.h) ============= */
#define ML_CLASS_SILENCE         0u
#define ML_CLASS_WIND            1u
#define ML_CLASS_CAVITATION      2u
#define ML_CLASS_CHAINSAW        3u
#define ML_CLASS_FAUNA           4u
#define NUM_CLASSES              5u
#define MODEL_INPUT_SIZE         40u
#define SNAM_HIDDEN              16
#define TENSOR_ARENA_SIZE        76u  /* int8 activations + logits — STACK; weights are const (Flash) -> ~0 .bss */

/* === Quantization parameters ========================================== */
#define SNAM_IN_SCALE   0.0814666599f
#define SNAM_IN_ZP      38
#define SNAM_H_ZP       (-128)
#define SNAM_OUT_ZP     11
#define SNAM_OUT_SCALE  0.227881074f

/* === Weights (Flash / .rodata) ======================================== */
static const int8_t SNAM_FC1_W[16][40] = {
  { 55, 62, 48, 69, 23, 19, 20, 2, 47, 30, 9, 69, 45, 13, 59, 43, 25, 2, -12, 29, 10, -34, -25, -48, -116, -77, -91, -23, -88, -66, -30, -80, -34, -15, -46, 35, 19, 67, 97, 127 },
  { -33, 0, -25, 7, -47, -45, -2, -2, 1, -2, -38, 4, -17, -10, -14, 7, -68, -17, 35, -69, -33, -37, -61, -23, -18, -83, -36, 7, -12, -16, 6, -56, 13, 43, 127, 44, -31, -58, -7, 51 },
  { 111, 69, 48, 37, 3, -77, -15, 7, -15, -29, -39, -24, -5, 20, -39, 4, -6, -31, -97, -62, -86, -45, -61, 21, -11, 10, 15, 25, 26, 61, 127, 54, 100, 11, -53, -42, 8, 12, -51, -70 },
  { -74, 7, 45, 68, -59, -37, -24, 2, 15, -52, -52, -14, 11, 30, -16, 7, 39, -50, -80, -16, 48, 91, 67, 108, 117, 91, 3, -13, 25, -62, -53, -127, -27, -24, -25, 3, -20, -38, -31, -10 },
  { -24, -31, -54, 17, 41, -51, -45, 29, 28, -38, -26, 0, 7, -6, 19, -48, -46, 31, -53, 42, -17, -26, 70, 2, 44, 127, 108, 93, 126, 64, 92, -4, -46, -45, -4, 3, -29, 8, -15, -118 },
  { 71, 0, -12, 34, 7, -20, -2, 33, 45, 38, 23, 25, 19, -14, 68, -13, 26, -30, -34, 36, -19, -56, 6, 69, 16, 117, 5, 6, -47, -41, -6, -29, -11, 36, 66, 3, 38, -34, -72, -127 },
  { 127, 3, -16, 49, 98, 55, 89, -9, 65, -2, 15, 62, -71, -58, -27, 17, 2, 1, -48, 6, 49, 12, 3, 75, 125, 17, -41, 20, 21, 38, -11, -108, 59, -50, 18, 63, -24, -118, -43, -67 },
  { 14, -30, 5, -41, -54, -37, -24, 59, 28, -53, 59, 17, 4, 64, -22, 102, -1, 50, 33, 82, 61, 53, 16, 94, 9, -25, -37, 104, -13, -2, -12, -77, 106, 57, 32, 12, 45, 69, 52, 127 },
  { -57, -11, -27, 12, 13, -5, 29, 31, -17, 5, 19, 12, 40, 13, 1, -50, -47, -47, -4, -45, -59, 0, -14, -30, -1, -50, 37, 30, 45, 41, -4, 113, 114, 86, 89, 92, 83, 127, 65, 49 },
  { -40, -77, -127, -101, -42, -98, -47, -52, -66, -105, -6, -69, -63, -98, 7, -61, -56, -7, -33, -41, 4, 4, 30, 81, 48, -29, 89, 14, 112, 74, -14, 118, -16, 20, -22, -35, -87, -60, -101, 58 },
  { -11, -39, -36, -31, 0, 47, 5, 2, 0, -7, 3, 52, 27, 1, 36, 68, 61, 10, 27, -26, 52, 76, 32, 62, -24, 24, -39, 11, 4, 8, 30, 12, 60, -61, -65, -127, -89, -93, -31, -3 },
  { -56, -53, -68, -54, -80, -50, -33, 19, -45, 15, -33, 38, 11, 40, 35, -36, -10, 60, 27, 15, 4, 29, 79, 64, 127, 50, 29, 126, 18, 3, 42, 0, -92, -10, -120, -73, 33, -5, -78, 10 },
  { 23, 21, 38, 45, 47, 40, 51, 31, 12, -42, -31, 25, -41, -55, -54, 49, 11, 26, -13, 51, 50, 12, 64, 52, 31, 9, 13, -24, 17, -5, 27, -69, -127, -12, -45, 21, -14, -8, -56, -4 },
  { -8, 28, 32, -69, -31, -23, -24, -38, -11, 6, -34, -66, -31, -42, -53, -59, 24, -2, 30, 63, 19, 112, 54, 74, 75, -21, 102, 64, 99, -20, 1, 43, -58, 2, 15, 38, -62, -58, -25, -127 },
  { 5, 52, 46, 31, 10, 29, 6, 37, -9, 22, 10, 29, 9, -32, -22, -37, -41, 10, -55, -42, -43, -9, -18, -36, -18, 0, -42, -33, -27, -43, -86, -30, -127, -86, 8, -49, 22, -10, 18, -36 },
  { 41, -20, 11, 69, 6, -15, -25, 86, 30, 43, 7, 38, -33, 93, 121, 60, 74, -24, 68, -13, 57, 63, 22, -2, 6, 34, 125, 22, 65, 38, -50, 79, 2, 23, -7, 31, -31, -40, -76, -127 }
};
static const int32_t SNAM_FC1_B[16] = { 5827, -13056, -4145, -4460, 8192, 3496, 118, 23652, 24105, -7616, -2064, 6371, -1888, 5590, -24327, 22886 };
static const int32_t SNAM_FC1_M[16] = { 1950030928, 1566547788, 2026229954, 1652052380, 1363910090, 1755101204, 2099419800, 1101993905, 1715273273, 1115533522, 1921385696, 1405714208, 1426050466, 1604331449, 1892527226, 1261975958 };
static const int32_t SNAM_FC1_S[16] = { -8, -8, -8, -8, -8, -8, -9, -8, -8, -8, -8, -8, -8, -8, -8, -8 };
static const int8_t SNAM_FC2_W[5][16] = {
  { -28, -46, -30, 6, -46, -86, -8, 22, -124, 83, -103, 114, -17, 2, -127, -62 },
  { -21, -49, 127, -118, -42, -7, 119, 106, -8, -124, 127, -5, 92, -115, 84, -2 },
  { -99, 61, -46, -53, 6, -58, -49, -2, 48, -10, -39, -127, -34, 3, 29, -38 },
  { 13, 5, -50, -64, 50, 52, -43, 4, 10, -81, -71, -33, -52, 127, -7, 41 },
  { 70, -46, 77, 127, 70, -81, -62, -40, 48, 0, 76, 29, 18, 39, -9, 2 }
};
static const int32_t SNAM_FC2_B[5] = { 923, -1465, 74, -20, 166 };
static const int32_t SNAM_FC2_M[5] = { 1353925323, 1943931696, 1958858966, 1652999595, 1454649053 };
static const int32_t SNAM_FC2_S[5] = { -8, -9, -8, -8, -8 };

/* === gemmlowp fixed-point requantize (bit-mirror of silken_ml.export) === */
static inline int32_t snam_srdhm(int32_t a, int32_t b) {
    int64_t ab, nudge;
    if (a == INT32_MIN && b == INT32_MIN) return INT32_MAX;
    ab = (int64_t)a * (int64_t)b;
    nudge = (ab >= 0) ? (int64_t)(1 << 30) : (int64_t)(1 - (1 << 30));
    return (int32_t)((ab + nudge) >> 31);
}
static inline int32_t snam_rdpot(int32_t x, int e) {
    int32_t mask, rem, thr;
    if (e == 0) return x;
    mask = (int32_t)(((int32_t)1 << e) - 1);
    rem = x & mask;
    thr = (mask >> 1) + (x < 0 ? 1 : 0);
    return (x >> e) + ((rem > thr) ? 1 : 0);
}
static inline int32_t snam_requant(int32_t x, int32_t q, int s) {
    if (s > 0) x <<= s;
    return (s < 0) ? snam_rdpot(snam_srdhm(x, q), -s) : snam_srdhm(x, q);
}
static inline int8_t snam_clamp8(int32_t v) {
    return (int8_t)(v < -128 ? -128 : (v > 127 ? 127 : v));
}

/* 40 log-mel floats -> class id [0,NUM_CLASSES); *confidence = softmax max in [0,1].
 * Heavy path is INT8 (FC -> ReLU -> FC, no-FPU friendly); only the final 5-way
 * softmax touches float (the confidence scalar). */
static inline uint8_t Run_Inference(const float* buffer, float* confidence) {
    int8_t a[MODEL_INPUT_SIZE];
    int8_t hbuf[SNAM_HIDDEN];
    int32_t logit[NUM_CLASSES];
    int i, j, k;
    uint8_t best;
    int32_t bestv;
    float sum;

    for (i = 0; i < (int)MODEL_INPUT_SIZE; i++)
        a[i] = snam_clamp8((int32_t)lrintf(buffer[i] / SNAM_IN_SCALE) + SNAM_IN_ZP);

    for (j = 0; j < SNAM_HIDDEN; j++) {
        int32_t acc = SNAM_FC1_B[j];
        for (i = 0; i < (int)MODEL_INPUT_SIZE; i++)
            acc += (int32_t)(a[i] - SNAM_IN_ZP) * (int32_t)SNAM_FC1_W[j][i];
        /* ReLU is implicit: SNAM_H_ZP is the quantized 0 (== int8 min) */
        hbuf[j] = snam_clamp8(snam_requant(acc, SNAM_FC1_M[j], SNAM_FC1_S[j]) + SNAM_H_ZP);
    }

    for (k = 0; k < (int)NUM_CLASSES; k++) {
        int32_t acc = SNAM_FC2_B[k];
        for (j = 0; j < SNAM_HIDDEN; j++)
            acc += (int32_t)(hbuf[j] - SNAM_H_ZP) * (int32_t)SNAM_FC2_W[k][j];
        acc = snam_requant(acc, SNAM_FC2_M[k], SNAM_FC2_S[k]) + SNAM_OUT_ZP;
        logit[k] = acc < -128 ? -128 : (acc > 127 ? 127 : acc);
    }

    best = 0; bestv = logit[0];
    for (k = 1; k < (int)NUM_CLASSES; k++)
        if (logit[k] > bestv) { bestv = logit[k]; best = (uint8_t)k; }
    sum = 0.0f;
    for (k = 0; k < (int)NUM_CLASSES; k++)
        sum += expf(((float)logit[k] - (float)bestv) * SNAM_OUT_SCALE);
    *confidence = 1.0f / sum;
    return best;
}

#endif /* SILKEN_NET_AUDIO_MODEL_H */
