#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# tools/firmware/gen_bytecode.sh — [FW.46] regenerate the committed mruby
# bytecode mirror firmware/common/lorenz_bytecode.h from bio_contract.rb.
#
# Builds the host mruby (if mrbc is absent) and runs `mrbc -B lorenz_bytecode`,
# wrapping the output with an include guard + a sha256 stamp of the source so
# the LIGHT stdlib gate (check_bytecode.py) can detect source-vs-mirror drift
# without needing mrbc.
#
#   tools/firmware/gen_bytecode.sh           # regenerate in place
#   tools/firmware/gen_bytecode.sh --check   # fail if regen != committed (CI)
#
# Determinism: mruby is pinned (firmware/extern/mruby submodule), the source is
# passed as a stable repo-relative path, and RITE bytecode is endian-stable, so
# regen is byte-reproducible across the dev box (arm64) and CI (x86).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
SRC_REL="firmware/bio_contracts/bio_contract.rb"
SRC="$REPO/$SRC_REL"
OUT="$REPO/firmware/common/lorenz_bytecode.h"
MRUBY="$REPO/firmware/extern/mruby"
MRBC="$MRUBY/build/host/bin/mrbc"
MRUBY_VER="4.0.0"

check=0
[ "${1:-}" = "--check" ] && check=1

if [ ! -x "$MRBC" ]; then
  echo "[FW.46] host mruby/mrbc absent — building…"
  ( cd "$MRUBY" && MRUBY_CONFIG="$REPO/firmware/mruby/build_config.rb" rake -j4 >/dev/null )
fi

sha="$(shasum -a 256 "$SRC" | awk '{print $1}')"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# mrbc emits `const uint8_t lorenz_bytecode[] = {…};` (no debug info without -g).
( cd "$REPO" && "$MRBC" -B lorenz_bytecode -o "$tmp/body.h" "$SRC_REL" )

{
  # [UNI.3] SPDX emitted by the generator, not by the header sweep: --check does a full
  # `diff` against the committed file, so a tag added afterwards would read as drift.
  echo "// SPDX-License-Identifier: AGPL-3.0-or-later"
  echo "/* GENERATED by tools/firmware/gen_bytecode.sh — DO NOT EDIT BY HAND."
  echo " *"
  echo " * Source:    firmware/bio_contracts/bio_contract.rb"
  echo " * mruby:     ${MRUBY_VER} (firmware/extern/mruby submodule)"
  echo " * float:     double (NO MRB_USE_FLOAT — FW.19 / FW.7 byte-parity)"
  echo " * bio_contract.rb sha256: ${sha}"
  echo " *"
  echo " * Regenerate: tools/firmware/gen_bytecode.sh"
  echo " * Drift-gate: tools/firmware/check_bytecode.py (light, stdlib)"
  echo " *             tools/firmware/gen_bytecode.sh --check (deep, needs mrbc)"
  echo " */"
  echo "#ifndef SILKEN_LORENZ_BYTECODE_H"
  echo "#define SILKEN_LORENZ_BYTECODE_H"
  echo ""
  cat "$tmp/body.h"   # mrbc -B already emits: #include <stdint.h> + const uint8_t …
  echo ""
  echo "#endif /* SILKEN_LORENZ_BYTECODE_H */"
} > "$tmp/lorenz_bytecode.h"

if [ "$check" = 1 ]; then
  if ! diff -q "$tmp/lorenz_bytecode.h" "$OUT" >/dev/null 2>&1; then
    echo "❌ [FW.46] lorenz_bytecode.h is stale vs bio_contract.rb — regenerate:"
    echo "   tools/firmware/gen_bytecode.sh"
    diff "$OUT" "$tmp/lorenz_bytecode.h" || true
    exit 1
  fi
  echo "✅ [FW.46] lorenz_bytecode.h matches bio_contract.rb"
else
  cp "$tmp/lorenz_bytecode.h" "$OUT"
  echo "✅ [FW.46] wrote $OUT (bio_contract.rb sha256 ${sha})"
fi
