# frozen_string_literal: true

module Api
  module V1
    # Persists the user's UI language preference in a permanent cookie and
    # bounces back to the page they came from. Designed to be a no-JS-needed
    # `button_to` target so that the switcher works even with disabled
    # JavaScript (progressive enhancement).
    #
    # CSRF protection (inherited from ApplicationController) stays enabled —
    # the form generated by `LocaleSwitcher` always includes the authenticity
    # token, so the endpoint is safe to expose to unauthenticated visitors.
    class LocalesController < ApplicationController
      def update
        raw = params[:locale]
        requested = raw.to_sym if raw.is_a?(String) && raw.present?

        if requested && I18n.available_locales.include?(requested)
          cookies.permanent[:locale] = {
            value: requested.to_s,
            same_site: :lax,
            httponly: true,
            secure: Rails.env.production?
          }
          I18n.locale = requested
          flash[:notice] = I18n.t("flash.locale_changed", lang: I18n.t("locale.available.#{requested}"))
        else
          flash[:alert] = I18n.t("flash.unsupported_locale")
        end

        redirect_back_or_to api_v1_root_path, status: :see_other
      end

      private

      # Helper: redirect back when safe, otherwise to fallback. Manual impl
      # so we don't depend on `redirect_back` exact behaviour across versions
      # and so we can sanitize against open-redirect.
      def redirect_back_or_to(fallback, **options)
        target = sanitized_referer || fallback
        redirect_to target, **options
      end

      def sanitized_referer
        ref = request.referer
        return nil if ref.blank?

        uri = URI.parse(ref)
        return nil unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS) || (uri.host.nil? && !uri.opaque)
        return nil unless uri.host.nil? || uri.host == request.host

        ref
      rescue URI::InvalidURIError
        nil
      end
    end
  end
end
