# SPDX-License-Identifier: AGPL-3.0-or-later
# frozen_string_literal: true

module Api
  module V1
    # Persists the user's UI language preference in a permanent cookie and
    # bounces back to the page they came from. Designed to be a no-JS-needed
    # `button_to` target so that the switcher works even with disabled
    # JavaScript (progressive enhancement).
    #
    # CSRF protection (inherited from ApplicationController) stays enabled —
    # the form generated by `LocaleSwitcher` always includes the authenticity
    # token, so the endpoint is safe to expose to unauthenticated visitors.
    class LocalesController < ApplicationController
      def update
        raw = params[:locale]
        requested = raw.to_sym if raw.is_a?(String) && raw.present?

        if requested && I18n.available_locales.include?(requested)
          # ⚠️ [I18N.3] `expires:` ЯВНО, і це не косметика: `cookies.permanent`
          # ставить **20 років** (`actionpack .../cookies.rb` → `20.years.from_now`),
          # тобто строк зберігання даних обирав дефолт фреймворку, а не ми. Обидва
          # наші носії наміру — `b2c_tos_privacy.md` §Cookies і його ж таблиця
          # Cookie Policy, тобто МАЙБУТНІЙ ПУБЛІЧНИЙ документ, — заявляють рік.
          # Розбіжність у 20× на функціональному cookie є заявою про retention,
          # яку ми не виконуємо, тож приводимо код до записаного наміру, а не
          # навпаки: рік для мовної вподоби достатній, 20 років — не мінімізація.
          cookies[:locale] = {
            value: requested.to_s,
            expires: 1.year.from_now,
            same_site: :lax,
            httponly: true,
            secure: Rails.env.production?
          }
          I18n.locale = requested
          remember_choice_for_signed_in_user(requested)
          flash[:success] = I18n.t("flash.locale_changed", lang: I18n.t("locale.available.#{requested}"))
        else
          flash[:error] = I18n.t("flash.unsupported_locale")
        end

        redirect_back_or_to root_path, status: :see_other
      end

      private

      # [I18N.1] Cookie тримає вибір для ЦЬОГО браузера; колонка — для всього
      # іншого, і причин у неї тепер ДВІ.
      #
      # (1) Пошта відправляється з Sidekiq (`deliver_later`), де ані cookie, ані
      #     сесії немає, тож без цього запису `users.locale` лишався б NULL
      #     назавжди, а `ApplicationMailer#in_locale_of` — декоративним.
      # (2) [I18N.3] Відколи колонка стоїть третім щаблем `LocaleSettable`, вона
      #     ще й переживає ЗМІНУ ПРИСТРОЮ: доти людина, що обрала мову тут,
      #     діставала англійський веб на новому браузері — і латиський лист.
      #     Тобто цей рядок доти був вужчим, ніж здавався: він рятував пошту й
      #     мовчки лишав веб.
      #
      # Гість лишається гостем: анонімний перемикач і далі працює (він і має —
      # перемикач стоїть на сторінці входу), просто нічого не персистить.
      #
      # ⚠️ Guard дзеркалить [SEC.16] з `Api::V1::BaseController#authenticate_user!`
      # (`session[:ps]` = хвіст `password_salt`), а не просто вірить `session[:user_id]`:
      # цей контролер успадковує `ApplicationController` — СЕСТРУ, не предка
      # `BaseController`, — тож власного `current_user` тут немає, і послабити
      # перевірку було б тихим обходом salt-прив'язки.
      #
      # `update_column` свідомо: значення вже провалідоване проти
      # `I18n.available_locales` вище, а мовна вподоба не мусить ані запускати
      # audit-ланцюг, ані падати через невалідне legacy-поле деінде в записі.
      # [I18N.3] Hook `LocaleSettable#locale_account` — і без нього щабель 3 був би
      # мертвий рівно тут, у контролері, який ВОЛОДІЄ перемиканням мови: сестра
      # `ApplicationController` не має `current_user`, тож дефолтний `nil` тихо
      # з'їдав би акаунт-вподобу. Тобто оголошений-і-недосяжний щабель — та сама
      # хвороба, що лікується цим пунктом, і повторити її на сусідньому корені
      # було б найтихішим способом лишити роботу недоробленою.
      # Наслідок конкретний: людина з `users.locale = "uk"` на новому пристрої
      # діставала б `flash[:error]` про невалідну локаль АНГЛІЙСЬКОЮ.
      def locale_account
        salt_verified_user
      end

      # Один дім salt-звіреного lookup'а в цьому контролері — його читають ОБИДВА
      # споживачі (hook вище + писач нижче).
      #
      # ⚠️ Мемоізації тут НЕМАЄ свідомо, і це виміряно, а не вгадано: `resolve_locale`
      # оцінює щаблі ЛІНИВО, а на `POST /locale` перший щабель (`params[:locale]`)
      # відповідає завжди — тож hook до цього методу просто не доходить, і виклик
      # лишається рівно один на запит по кожному досяжному шляху. Мемо-гілка
      # `defined?` була б недосяжна за побудовою (спіймано branch-coverage, не оком),
      # тобто мертвим кодом, який виглядає як дбайливість.
      def salt_verified_user
        user = User.find_by(id: session[:user_id]) if session[:user_id].present?
        user if user && session[:ps].to_s == user.password_salt.to_s.last(10)
      end

      def remember_choice_for_signed_in_user(locale)
        user = salt_verified_user
        return if user.nil? || user.locale == locale.to_s

        user.update_column(:locale, locale.to_s)
      end

      # Helper: redirect back when safe, otherwise to fallback. Manual impl
      # so we don't depend on `redirect_back` exact behaviour across versions
      # and so we can sanitize against open-redirect.
      def redirect_back_or_to(fallback, **options)
        target = sanitized_referer || fallback
        redirect_to target, **options
      end

      def sanitized_referer
        ref = request.referer
        return nil if ref.blank?

        uri = URI.parse(ref)
        return nil unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS) || (uri.host.nil? && !uri.opaque)
        return nil unless uri.host.nil? || uri.host == request.host

        ref
      rescue URI::InvalidURIError
        nil
      end
    end
  end
end
