#!/usr/bin/env ruby
# SPDX-License-Identifier: AGPL-3.0-or-later
# frozen_string_literal: true

# [UNI.3] SPDX per-file licence headers — idempotent rollout engine.
#
# WHY THIS EXISTS. The repository carries four licences (AGPL-3.0-or-later for code,
# MIT for contracts/, CERN-OHL-S-2.0 for hardware design, CC-BY-SA-4.0 for docs) but
# states them only in root LICENSE files. Automated licence scanners (SPDX/SBOM tools,
# GitHub's detector, an enterprise buyer's SCA pass) read per-file identifiers; without
# them ~1400 tracked source files read as *unlicensed*, which is the opposite of what a
# defensive-publication, copyleft-enforcement posture needs. Posture → docs/07_03 §3;
# audit + ratified scope → docs/protocols/legal/spdx_rollout_plan.md; state → 00_07 UNI.3.
#
# ENUMERATION IS `git ls-files`, NEVER `find` / `grep -r`. This is the single most
# important guardrail from the audit. A raw filesystem walk sees ~1440 files already
# carrying SPDX tags, but essentially all of them live inside git submodules
# (firmware/extern/*, tools/cad/extern/*) or gitignored build output
# (contracts/node_modules, contracts/out, medusa corpora). Writing there means editing
# another project's checkout, or writing into files the next `forge build` / `npm ci`
# overwrites. Through `git ls-files` a submodule is a single gitlink entry, so its
# contents are structurally invisible and cannot be reached by accident.
#
# 🔴 THE FINDING THAT REVERSED THE WRITTEN PLAN. spdx_rollout_plan.md §5.3 prescribed
# inserting the tag *after* Ruby magic comments ("НІКОЛИ перед ними"), on the theory
# that a line above `# frozen_string_literal: true` silently disables it. Measured on
# Ruby 4.0.5 with a negative control, that theory is false: the magic comment is honoured
# anywhere in the leading comment block, with or without a shebang above it. The
# prescription was not merely unnecessary — it was actively harmful, because a comment
# placed directly after the magic comment trips RuboCop's
# Layout/EmptyLineAfterMagicComment, which would have turned ~999 Ruby files red in one
# commit. Hence the rule implemented here: **line 1, or line 2 when a shebang owns line
# 1 — never after the magic comment.** Verified clean for all four Ruby shapes present in
# this repo (magic-first, shebang+magic, plain-comment-first, code-first).
#
# NAMED CEILINGS (deliberate exclusions, not oversights):
#   · *.erb — an ERB comment emits a blank line into RENDERED output;
#     app/views/pwa/manifest.json.erb serves JSON and layouts/application.html.erb would
#     gain whitespace before <!DOCTYPE>. A `<%# ... -%>` trim form exists and was rejected
#     as clever-over-boring (CLAUDE.md §4). Founder call, 2026-07-26.
#   · db/structure.sql — regenerated by pg_dump on every schema change, so a header is
#     wiped and, worse, shows up as a phantom minus-line in every future dump review.
#   · config/locales/** (136 files) — the CI step "Check locale YAML files are normalized"
#     compares each file BYTE-FOR-BYTE against a freshly rendered dump
#     (i18n-tasks file_formats.rb#normalized?), and that dump is produced by
#     Hash#to_yaml from a YAML.safe_load parse, which never captured a comment in the
#     first place. No position in the file survives — and the remedy the CI itself
#     suggests, `i18n-tasks normalize`, would silently DELETE the header on its next run
#     rather than fail loudly. Ceiling, with an upgrade path: locale-data licensing
#     belongs in an out-of-band declaration (REUSE `.reuse/dep5` or a directory LICENSE),
#     not an in-file comment. Everything else under config/ (45 files) is unaffected —
#     i18n-tasks reads only `config/locales/**`.
#   · *.json — strict JSON has no comment syntax; a header would break the file.
#   · docs/**, build plumbing (CMakeLists/*.cmake/*.ld/Makefile), .github/.claude/.kamal,
#     bin/ binstubs (generated by `bundle binstubs`, not our original work — the two
#     hand-written bin/*.sh ARE included).
#
# SELF-BLINDNESS, named because it is real: detection scans the first 15 lines for the
# literal `SPDX-License-Identifier`, so a source file that merely *discusses* the string
# near its top would be skipped as already-tagged. Exactly two files in this repo do
# that — this script and its spec — and both carry a genuine tag, so the skip is correct.
# Any future file of that shape must be tagged by hand.
#
# Pure Ruby, no Rails, no bundle. Read-only unless `--write` is passed.
#
#   ruby scripts/spdx_headers.rb                  # dry-run, whole repo
#   ruby scripts/spdx_headers.rb app lib          # dry-run, scoped to trees
#   ruby scripts/spdx_headers.rb app --write      # insert
#   ruby scripts/spdx_headers.rb --check          # exit 1 if anything is untagged (CI shape)
#   ruby scripts/spdx_headers.rb --verbose        # + resulting head of each file

module SpdxHeaders
  AGPL = "AGPL-3.0-or-later"
  MIT  = "MIT"

  # How many leading lines are searched for an existing tag. Generous on purpose: the
  # CubeMX insertion point sits inside the USER CODE Header block, a few lines down.
  SCAN_LINES = 15

  TAG_RE = /SPDX-License-Identifier:\s*(\S+)/

  # An extensionless file counts as source only when a shebang names an interpreter
  # whose comment character is `#` (lib/daemons/coap_listener is the sole case today).
  SHEBANG_HASH_LANG = /\A#!.*\b(?:ruby|python[\d.]*|bash|sh|zsh|perl)\b/

  LINE_COMMENT = {
    ".rb" => "#", ".rake" => "#", ".py" => "#", ".sh" => "#", ".tf" => "#",
    ".yml" => "#", ".yaml" => "#",
    ".c" => "//", ".h" => "//", ".cs" => "//", ".ts" => "//", ".js" => "//", ".sol" => "//"
  }.freeze

  # Checked FIRST — a deny hit wins over any allow rule below.
  DENY = [
    %r{(?:\A|/)extern/},                       # git submodules: another repository's code
    %r{\Adocs/},                               # CC-BY-SA via LICENSE-DOCS; no per-file tag by convention
    %r{\A\.github/}, %r{\A\.claude/}, %r{\A\.kamal/},
    %r{\Apublic/}, %r{\Avendor/},
    %r{\Adb/structure\.sql\z},                 # pg_dump regenerates it; header would be wiped
    %r{\Aconfig/locales/},                     # i18n-tasks re-renders these — see below
    %r{\.erb\z},                               # emits into rendered output — named ceiling
    %r{\.enc\z}, %r{\.key\z},                  # encrypted blobs: never touched
    %r{\Acontracts/(?:node_modules|out|cache|crytic-export|medusa-corpus)}
  ].freeze

  # Allow-list: a file is touched ONLY if some rule names its tree AND its extension.
  # Anything unlisted is left alone by construction — the safe default for a sweep of
  # this size. `""` admits extensionless files, still gated on the shebang test above.
  ALLOW = [
    [ "contracts/", %w[.sol],                MIT ],
    [ "app/",       %w[.rb .rake .js],       AGPL ],
    [ "lib/",       %w[.rb .rake ""],        AGPL ],
    [ "spec/",      %w[.rb],                 AGPL ],
    [ "scripts/",   %w[.rb],                 AGPL ],
    [ "db/",        %w[.rb .yml],            AGPL ],
    [ "config/",    %w[.rb .yml .yaml],      AGPL ],
    [ "firmware/",  %w[.c .h .rb .py .sh],   AGPL ],
    [ "tools/",     %w[.py .rb .sh .cs],     AGPL ],
    [ "terraform/", %w[.tf .sh],             AGPL ],
    [ "subgraph/",  %w[.ts .sh],             AGPL ],
    [ "deploy/",    %w[.rb .sh],             AGPL ],
    [ "bin/",       %w[.sh],                 AGPL ]
  ].freeze

  module_function

  # Repo-relative paths of tracked files, optionally narrowed to `paths`.
  def tracked_files(root, paths = [])
    IO.popen([ "git", "-C", root, "ls-files", "-z", *paths ], &:read)
      .split("\0").reject(&:empty?)
  end

  # The licence a path is due, or nil when it is out of scope.
  def licence_for(path)
    return nil if DENY.any? { |re| re.match?(path) }

    ext = File.extname(path)
    rule = ALLOW.find { |prefix, exts, _| path.start_with?(prefix) && exts.include?(ext) }
    rule&.last
  end

  # The comment prefix to use, or nil when the file has no usable comment syntax.
  def comment_prefix(path, first_line)
    ext = File.extname(path)
    return LINE_COMMENT[ext] if LINE_COMMENT.key?(ext)
    return "#" if ext.empty? && SHEBANG_HASH_LANG.match?(first_line.to_s)

    nil
  end

  # Index at which the tag line is inserted. Three shapes, and each exists in this repo:
  #   · CubeMX C — INSIDE the USER CODE Header block, so a regen cannot silently drop it
  #   · YAML     — after a leading `---` / `%YAML` directive (the majority case here)
  #   · anything else — line 0, or line 1 when a shebang owns line 0
  def insertion_index(path, lines)
    case File.extname(path)
    when ".c", ".h"
      i = lines.first(SCAN_LINES).index { |l| l.include?("USER CODE BEGIN Header") }
      i ? i + 1 : 0
    when ".yml", ".yaml"
      lines[0].to_s.start_with?("---", "%YAML") ? 1 : 0
    else
      lines[0].to_s.start_with?("#!") ? 1 : 0
    end
  end

  def existing_tag(lines)
    lines.first(SCAN_LINES).each do |line|
      m = TAG_RE.match(line)
      return m[1] if m
    end
    nil
  end

  # One planned action per in-scope file. Never writes.
  #   :insert        — needs the tag
  #   :ok            — already carries the expected tag
  #   :mismatch      — carries a DIFFERENT tag; reported, never rewritten
  #   :unsupported   — in scope by tree but no comment syntax / unreadable
  def plan(root: Dir.pwd, paths: [])
    tracked_files(root, paths).filter_map do |rel|
      licence = licence_for(rel)
      next if licence.nil?

      abs = File.join(root, rel)
      next unless File.file?(abs)

      body = File.binread(abs)
      next if body.empty?
      next if body.include?("\0") # binary that slipped the extension allow-list

      lines = body.force_encoding(Encoding::UTF_8).lines
      prefix = comment_prefix(rel, lines[0])
      next { path: rel, status: :unsupported, licence: } if prefix.nil?

      found = existing_tag(lines)
      status = if found.nil?      then :insert
      elsif found == licence then :ok
      else :mismatch
      end

      { path: rel, status:, licence:, found:, prefix:,
        index: insertion_index(rel, lines),
        eol: lines[0].end_with?("\r\n") ? "\r\n" : "\n" }
    end
  end

  # Applies one :insert action. Returns the resulting leading lines (for review).
  def apply!(root, action)
    abs = File.join(root, action[:path])
    lines = File.readlines(abs)
    lines.insert(action[:index], "#{action[:prefix]} SPDX-License-Identifier: #{action[:licence]}#{action[:eol]}")
    File.write(abs, lines.join)
    lines.first(4)
  end
end

if __FILE__ == $PROGRAM_NAME
  root    = File.expand_path("..", __dir__)
  write   = ARGV.delete("--write")
  check   = ARGV.delete("--check")
  verbose = ARGV.delete("--verbose")
  paths   = ARGV.reject { |a| a.start_with?("--") }

  actions   = SpdxHeaders.plan(root:, paths:)
  inserts   = actions.select { |a| a[:status] == :insert }
  mismatch  = actions.select { |a| a[:status] == :mismatch }
  unsupported = actions.select { |a| a[:status] == :unsupported }
  ok        = actions.count { |a| a[:status] == :ok }

  unless mismatch.empty?
    warn "spdx_headers — #{mismatch.size} file(s) carry a DIFFERENT identifier than the scope map expects."
    warn "These are never rewritten automatically; resolve by hand or fix the map (07_03 §3):"
    mismatch.each { |a| warn "  ⚠ #{a[:path]} — found #{a[:found]}, map says #{a[:licence]}" }
    warn ""
  end

  unless unsupported.empty?
    warn "spdx_headers — #{unsupported.size} in-scope file(s) have no usable comment syntax (skipped):"
    unsupported.each { |a| warn "  · #{a[:path]}" }
    warn ""
  end

  if check
    if inserts.empty?
      puts "spdx_headers ✓ — every in-scope file carries its SPDX identifier (#{ok} tagged)."
      exit mismatch.empty? ? 0 : 1
    end
    warn "spdx_headers ✗ — #{inserts.size} in-scope file(s) missing an SPDX identifier (00_07 UNI.3):"
    inserts.first(40).each { |a| warn "  ✗ #{a[:path]}" }
    warn "  … and #{inserts.size - 40} more" if inserts.size > 40
    exit 1
  end

  by_tree = inserts.group_by { |a| a[:path][%r{\A[^/]+}] }

  if inserts.empty?
    puts "spdx_headers — nothing to do (#{ok} file(s) already tagged in this scope)."
  elsif write
    inserts.each do |a|
      head = SpdxHeaders.apply!(root, a)
      puts "  + #{a[:path]}"
      head.each { |l| puts "      #{l.chomp}" } if verbose
    end
    puts "\nspdx_headers — WROTE #{inserts.size} header(s); #{ok} already tagged."
    by_tree.sort.each { |tree, list| puts "  #{tree}/ — #{list.size}" }
    puts "\nNow run the tree's gate (CLAUDE.md §3) before committing."
  else
    inserts.each do |a|
      puts "  [DRY-RUN] #{a[:path]}:#{a[:index] + 1} ← #{a[:prefix]} SPDX-License-Identifier: #{a[:licence]}"
    end
    puts "\nspdx_headers — DRY-RUN: would insert #{inserts.size} header(s); #{ok} already tagged."
    by_tree.sort.each { |tree, list| puts "  #{tree}/ — #{list.size}" }
    puts "\nRe-run with --write to apply. Nothing was modified."
  end
end
