"""Emit the committed firmware log-mel tables + golden vectors (C headers).

Generates three headers into ``firmware/common/`` from the pure-stdlib oracle:

  * ``logmel_hann_table.h``     — periodic Hann window (512 × float32)
  * ``logmel_mel_bank.h``       — HTK mel bank as a sparse ``(m, k, w)`` triplet
  * ``logmel_golden_vectors.h`` — deterministic input frames → expected log-mel

Each header is stamped with the contract hash (``docs/03_03 §3.4``) so a silent
contract edit on any side turns the drift check red.

Usage::

    python -m silken_ml.codegen.emit_c               # write to firmware/common/
    python -m silken_ml.codegen.emit_c --check       # verify committed == regen
    python -m silken_ml.codegen.emit_c --out DIR     # write elsewhere

Exit code 1 on ``--check`` drift (CI gate).
"""

from __future__ import annotations

import argparse
import math
import struct
import sys
from pathlib import Path

from ..dsp import logmel_stdlib as L
from ..dsp.contract import CONTRACT, contract_hash

_GENERATED_BY = "tools/ml/src/silken_ml/codegen/emit_c.py"


# ── float helpers ────────────────────────────────────────────────────────────
def f32(x: float) -> float:
    """Round a Python double to its float32 value (what the C literal becomes)."""
    return struct.unpack("f", struct.pack("f", x))[0]


def c_float(x: float) -> str:
    """Format a float as a round-trip-safe C ``float`` literal.

    ``%.9g`` round-trips float32, but drops the point for whole numbers
    (``0.0 → "0"``) — and ``0f`` is an *invalid octal constant* in C. Ensure a
    ``.``/``e`` is present so the literal is always a valid float.
    """
    s = f"{f32(x):.9g}"
    if not any(ch in s for ch in ".eEnN"):  # n/N catch inf/nan spellings
        s += ".0"
    return s + "f"


def _banner(name: str, guard: str) -> str:
    return (
        f"/* {name} — AUTO-GENERATED by {_GENERATED_BY}. DO NOT EDIT.\n"
        f" * Source of truth: docs/03_03 §3.4 (contract hash {contract_hash()}).\n"
        f" * Regenerate: python -m silken_ml.codegen.emit_c   (verify: --check)\n"
        f" */\n"
        f"#ifndef {guard}\n#define {guard}\n\n"
    )


# ── header generators ────────────────────────────────────────────────────────
def gen_hann() -> str:
    c = CONTRACT
    win = L.periodic_hann(c.n_fft)
    out = [_banner("logmel_hann_table.h", "LOGMEL_HANN_TABLE_H")]
    out.append(f"/* Periodic Hann (fftbins=True), denom N={c.n_fft}. */\n")
    out.append(f"static const float LOGMEL_HANN[{c.n_fft}] = {{\n")
    for i in range(0, c.n_fft, 6):
        row = ", ".join(c_float(win[j]) for j in range(i, min(i + 6, c.n_fft)))
        out.append(f"    {row},\n")
    out.append("};\n\n#endif /* LOGMEL_HANN_TABLE_H */\n")
    return "".join(out)


def gen_mel_bank() -> str:
    c = CONTRACT
    fb = L.mel_filterbank(c)
    triplets = [(m, k, fb[m][k])
                for m in range(c.n_mels) for k in range(c.n_bins) if fb[m][k] > 0.0]
    out = [_banner("logmel_mel_bank.h", "LOGMEL_MEL_BANK_H")]
    out.append("#include <stdint.h>\n\n")
    out.append("/* HTK mel bank (norm=None), sparse triplet: out_mel[m] += w * power[k]. */\n")
    out.append(f"#define LOGMEL_MEL_NNZ {len(triplets)}\n\n")
    out.append("typedef struct { uint8_t m; uint16_t k; float w; } logmel_mel_triplet_t;\n\n")
    out.append("static const logmel_mel_triplet_t LOGMEL_MEL_BANK[LOGMEL_MEL_NNZ] = {\n")
    for (m, k, w) in triplets:
        out.append(f"    {{ {m:2d}, {k:3d}, {c_float(w)} }},\n")
    out.append("};\n\n#endif /* LOGMEL_MEL_BANK_H */\n")
    return "".join(out)


def _golden_inputs() -> list[tuple[str, list[float]]]:
    """Deterministic synthetic frames — reproducible, embedded verbatim."""
    n, sr = CONTRACT.n_fft, CONTRACT.sr
    cases: list[tuple[str, list[float]]] = []
    cases.append(("silence", [0.0] * n))
    # Constant 0.5 → after per-frame DC removal must collapse to silence.
    cases.append(("dc_half", [0.5] * n))
    # Tones (offset 0.5 to stay in [0,1)); energy should land in the bin's mel band.
    for bin_k in (16, 64, 128):
        f = bin_k * sr / n
        cases.append((f"tone_bin{bin_k}",
                      [0.5 + 0.4 * math.sin(2.0 * math.pi * f * i / sr) for i in range(n)]))
    # Deterministic pseudo-noise (LCG) in [0,1) — no numpy needed.
    seed = 0x2545F4914F6CDD1D
    noise = []
    for _ in range(n):
        seed = (6364136223846793005 * seed + 1442695040888963407) & ((1 << 64) - 1)
        noise.append((seed >> 11) / float(1 << 53))
    cases.append(("noise_lcg", noise))
    return cases


def gen_golden() -> str:
    c = CONTRACT
    cases = _golden_inputs()
    out = [_banner("logmel_golden_vectors.h", "LOGMEL_GOLDEN_VECTORS_H")]
    out.append(f"#define LOGMEL_GOLDEN_COUNT {len(cases)}\n")
    out.append(f"#define LOGMEL_GOLDEN_N_FFT {c.n_fft}\n")
    out.append(f"#define LOGMEL_GOLDEN_N_MELS {c.n_mels}\n\n")
    out.append("typedef struct {\n")
    out.append("    const char* name;\n")
    out.append(f"    float input[{c.n_fft}];\n")
    out.append(f"    float expected[{c.n_mels}];\n")
    out.append("} logmel_golden_t;\n\n")
    out.append("static const logmel_golden_t LOGMEL_GOLDEN[LOGMEL_GOLDEN_COUNT] = {\n")
    for name, audio in cases:
        expected = L.compute_logmel_frame(audio, c)
        out.append(f'  {{ "{name}",\n')
        out.append("    {\n")
        for i in range(0, c.n_fft, 6):
            row = ", ".join(c_float(audio[j]) for j in range(i, min(i + 6, c.n_fft)))
            out.append(f"      {row},\n")
        out.append("    },\n    {\n")
        for i in range(0, c.n_mels, 6):
            row = ", ".join(c_float(expected[j]) for j in range(i, min(i + 6, c.n_mels)))
            out.append(f"      {row},\n")
        out.append("    } },\n")
    out.append("};\n\n#endif /* LOGMEL_GOLDEN_VECTORS_H */\n")
    return "".join(out)


HEADERS = {
    "logmel_hann_table.h": gen_hann,
    "logmel_mel_bank.h": gen_mel_bank,
    "logmel_golden_vectors.h": gen_golden,
}


def default_out_dir() -> Path:
    # …/repo/tools/ml/src/silken_ml/codegen/emit_c.py → parents[5] = repo root
    return Path(__file__).resolve().parents[5] / "firmware" / "common"


def write_all(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, gen in HEADERS.items():
        (out_dir / name).write_text(gen(), encoding="utf-8")
        print(f"  wrote {out_dir / name}")


def check_all(out_dir: Path) -> int:
    drift = 0
    for name, gen in HEADERS.items():
        path = out_dir / name
        want = gen()
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have != want:
            drift += 1
            state = "MISSING" if have is None else "DRIFT"
            print(f"  ✗ {name}: {state} — run `python -m silken_ml.codegen.emit_c`")
        else:
            print(f"  ✓ {name}")
    return drift


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Emit / verify firmware log-mel tables.")
    ap.add_argument("--out", type=Path, default=None, help="output dir (default firmware/common)")
    ap.add_argument("--check", action="store_true", help="verify committed == regen (exit 1 on drift)")
    args = ap.parse_args(argv)
    out_dir = args.out or default_out_dir()

    print(f"log-mel codegen — contract {contract_hash()} → {out_dir}")
    if args.check:
        drift = check_all(out_dir)
        if drift:
            print(f"\n❌ {drift} header(s) drifted from the contract.")
            return 1
        print("\n✅ all firmware log-mel headers match the contract.")
        return 0
    write_all(out_dir)
    print("✅ generated. Run with --check in CI to catch drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
